version: "3.7"
services:

  nginx:
    hostname: nginx
    container_name: nginx
    build: './nginx'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm
      - nodejs
    networks:
      - backend_exemplo

  php-fpm:
    hostname: php-fpm
    container_name: php-fpm
    build: './php-fpm'
    volumes:
      - ./www/php:/var/www
    networks:
      - backend_exemplo

  nodejs:
    hostname: nodejs
    container_name: nodejs
    build: './nodejs'
    volumes:
      - ./www/node:/usr/src/www
    networks:
      - backend_exemplo

networks:
  backend_exemplo:
    driver: bridge
